-- FF_CUSTOMERS
CREATE OR REPLACE TABLE FF_CUSTOMERS (
    CUSTOMER_ID NUMBER PRIMARY KEY,
    CONTACT_LAST_NAME   VARCHAR(100),
    CONTACT_FIRST_NAME  VARCHAR(100),
    STREET              VARCHAR(200),
    CITY                VARCHAR(100),
    STATE               VARCHAR(50),
    ZIP                 VARCHAR(20),
    COUNTRY             VARCHAR(50),
    AGE                 NUMBER(3),
    MARITAL_STATUS      VARCHAR(20),
    GENDER              VARCHAR(10),
    NUMBER_OF_DEPENDENTS NUMBER(2)
);

-- FF_ASSET_OBJECTIVES
CREATE OR REPLACE TABLE FF_ASSET_OBJECTIVES (
    ASSET_OBJECTIVE_ID NUMBER(8) PRIMARY KEY,
    ASSET_OBJECTIVE_NAME VARCHAR(20)
);

-- FF_CUSTOMER_ASSETS
CREATE OR REPLACE TABLE FF_CUSTOMER_ASSETS (
    CUSTOMER_ASSET_OBJECTIVE_ID NUMBER(8) PRIMARY KEY,
    CUSTOMER_ID NUMBER(8),
    ASSET_OBJECTIVE_ID NUMBER(8),
    TOTAL NUMBER(18,2)
);


-- FF_QUESTIONS
CREATE OR REPLACE TABLE FF_QUESTIONS (
    QUESTION_ID NUMBER(8) PRIMARY KEY,
    QUESTION_SUBJECT VARCHAR(50),
    QUESTION_TEXT VARCHAR(200)
);

-- FF_RISK_PROFILES
CREATE OR REPLACE TABLE FF_RISK_PROFILES (
    RISK_PROFILE_ID NUMBER(8) PRIMARY KEY,
    RISK_PROFILE VARCHAR(50)
);

-- FF_ANSWERS
CREATE OR REPLACE TABLE FF_ANSWERS (
    QUESTION_ANSWER_ID NUMBER(8) PRIMARY KEY,
    QUESTION_ID NUMBER(8),
    ANSWER_ID NUMBER(8),
    ANSWER_TEXT VARCHAR(100),
    RISK_PROFILE_ID NUMBER(8)
);


-- FF_CUSTOMER_ANSWERS
CREATE OR REPLACE TABLE FF_CUSTOMER_ANSWERS (
    CUSTOMER_QUESTION_ANSWER_ID NUMBER(8) PRIMARY KEY,
    CUSTOMER_ID NUMBER(8),
    QUESTION_ANSWER_ID NUMBER(8)
);


-- FF_ASSET_CLASSES
CREATE OR REPLACE TABLE FF_ASSET_CLASSES (
    ASSET_CLASS_ID NUMBER(8) PRIMARY KEY,
    ASSET_CLASS VARCHAR(20),
    RISK_PROFILE_ID NUMBER(8),
    FLAT_FEE NUMBER(10, 2),
    PERCENTAGE_FEE NUMBER(8, 5)
);


-- FF_POTENTIAL_FUNDS
CREATE OR REPLACE TABLE FF_POTENTIAL_FUNDS (
    FUND_ID NUMBER(8) PRIMARY KEY,
    FUND_NAME VARCHAR(30),
    FUND_DESCRIPTION VARCHAR(200),
    MINIMUM_INVESTMENT_REQUIRED NUMBER(10,2),
    MAXIMUM_INVESTMENT_ALLOWED NUMBER(10,2)
);

-- FF_FUND_ASSETS
CREATE OR REPLACE TABLE FF_FUND_ASSETS (
    FUND_ASSET_CLASS_ID NUMBER(8) PRIMARY KEY,
    FUND_ID NUMBER(8),
    ASSET_CLASS_ID NUMBER(8),
    PERCENT_OF_FUND NUMBER(5,2)
);


-- FF_CUSTOMER_FUNDS
CREATE OR REPLACE TABLE FF_CUSTOMER_FUNDS (
    CUSTOMER_FUND_ID NUMBER(8) PRIMARY KEY,
    CUSTOMER_ID NUMBER(8),
    FUND_ID NUMBER(8),
    AMOUNT_INVESTED NUMBER(15,2)
);


-- FF_ENGAGEMENT_FREQUENCIES
CREATE OR REPLACE TABLE FF_ENGAGEMENT_FREQUENCIES (
    FREQUENCY_ID NUMBER(8) PRIMARY KEY,
    FREQUENCY_NAME VARCHAR(20),
    FREQUENCY_CODE VARCHAR(2)
);

-- FF_ENGAGEMENT_TYPES
CREATE OR REPLACE TABLE FF_ENGAGEMENT_TYPES (
    ENGAGEMENT_TYPE_ID NUMBER(8) PRIMARY KEY,
    ENGAGEMENT_TYPE_NAME VARCHAR(10),
    ENGAGEMENT_TYPE_CODE VARCHAR(5)
);

-- FF_FUND_TARGETS
CREATE OR REPLACE TABLE FF_FUND_TARGETS (
    FUND_ID NUMBER(8) PRIMARY KEY,
    ASSET_OBJECTIVE_ID NUMBER(8),
    ENGAGEMENT_TYPE_ID NUMBER(8),
    FREQUENCY_ID NUMBER(8),
    TARGET_DESCRIPTION VARCHAR(100)
);


-- FF_CEP
CREATE OR REPLACE TABLE FF_CEP (
    CUSTOMER_ID NUMBER(8) PRIMARY KEY,
    ENGAGEMENT_TYPE_ID NUMBER(8),
    FREQUENCY_ID NUMBER(8)
);

