--15 TABLE
-- FF_CUSTOMERS
CREATE TABLE FF_CUSTOMERS (
    CUSTOMER_ID NUMBER PRIMARY KEY,
    CONTACT_LAST_NAME   VARCHAR2(100),
    CONTACT_FIRST_NAME  VARCHAR2(100),
    STREET              VARCHAR2(200),
    CITY                VARCHAR2(100),
    STATE               VARCHAR2(50),
    ZIP                 VARCHAR2(20),
    COUNTRY             VARCHAR2(50),
    AGE                 NUMBER(3),
    MARITAL_STATUS      VARCHAR2(20),
    GENDER              VARCHAR2(10),
    NUMBER_OF_DEPENDENTS NUMBER(2)
);

-- FF_ASSET_OBJECTIVES
CREATE TABLE FF_ASSET_OBJECTIVES (
    ASSET_OBJECTIVE_ID NUMBER(8) PRIMARY KEY,
    ASSET_OBJECTIVE_NAME VARCHAR2(20)
);

-- FF_CUSTOMER_ASSETS
CREATE TABLE FF_CUSTOMER_ASSETS (
    CUSTOMER_ASSET_OBJECTIVE_ID NUMBER(8) PRIMARY KEY,
    CUSTOMER_ID NUMBER(8),
    ASSET_OBJECTIVE_ID NUMBER(8),
    TOTAL NUMBER(18,2)
);

ALTER TABLE FF_CUSTOMER_ASSETS ADD CONSTRAINT FK_CUSTOMER_ID_CUST_ASSETS_TABLE FOREIGN KEY (CUSTOMER_ID) REFERENCES FF_CUSTOMERS (CUSTOMER_ID);
ALTER TABLE FF_CUSTOMER_ASSETS ADD CONSTRAINT FK_ASSET_OBJ_ID_CUST_ASSETS_TABLE FOREIGN KEY (ASSET_OBJECTIVE_ID) REFERENCES FF_ASSET_OBJECTIVES (ASSET_OBJECTIVE_ID);

-- FF_QUESTIONS
CREATE TABLE FF_QUESTIONS(
	QUESTION_ID NUMBER(8) PRIMARY KEY,
	QUESTION_SUBJECT VARCHAR2(50),
	QUESTION_TEXT VARCHAR2(200)
);

-- FF_RISK_PROFILES
CREATE TABLE FF_RISK_PROFILES(
    RISK_PROFILE_ID NUMBER(8) PRIMARY KEY,
    RISK_PROFILE VARCHAR2(50)
);

-- FF_ANSWERS
CREATE TABLE FF_ANSWERS(
    QUESTION_ANSWER_ID NUMBER(8) PRIMARY KEY,
    QUESTION_ID NUMBER(8),
    ANSWER_ID NUMBER(8),
    ANSWER_TEXT VARCHAR2(100),
    RISK_PROFILE_ID NUMBER(8)
);

ALTER TABLE FF_ANSWERS ADD CONSTRAINT FK_QUESTION_ID_ANSWERS_TABLE FOREIGN KEY (QUESTION_ID) REFERENCES FF_QUESTIONS (QUESTION_ID);
ALTER TABLE FF_ANSWERS ADD CONSTRAINT FK_RISK_ID_ANSWERS_TABLE FOREIGN KEY (RISK_PROFILE_ID) REFERENCES FF_RISK_PROFILES (RISK_PROFILE_ID);

-- FF_CUSTOMER_ANSWERS
CREATE TABLE FF_CUSTOMER_ANSWERS (
	CUSTOMER_QUESTION_ANSWER_ID NUMBER(8) PRIMARY KEY,
	CUSTOMER_ID NUMBER(8),
	QUESTION_ANSWER_ID NUMBER(8)
);

ALTER TABLE FF_CUSTOMER_ANSWERS ADD CONSTRAINT FK_CUSTOMER_ID_CUST_ANS_TABLE FOREIGN KEY (CUSTOMER_ID) REFERENCES FF_CUSTOMERS (CUSTOMER_ID);
ALTER TABLE FF_CUSTOMER_ANSWERS ADD CONSTRAINT FK_QUESTION_ANSWER_CUST_ANS_TABLE FOREIGN KEY (QUESTION_ANSWER_ID) REFERENCES FF_ANSWERS (QUESTION_ANSWER_ID);

-- FF_ASSET_CLASSES
CREATE TABLE FF_ASSET_CLASSES(
    ASSET_CLASS_ID NUMBER(8) PRIMARY KEY,
    ASSET_CLASS VARCHAR2(20),
    RISK_PROFILE_ID NUMBER(8),
    FLAT_FEE NUMBER(10, 2),
    PERCENTAGE_FEE NUMBER(8, 5)
);

ALTER TABLE FF_ASSET_CLASSES ADD CONSTRAINT FK_RISK_ID_ASSET_CLASSES_TABLE FOREIGN KEY (RISK_PROFILE_ID) REFERENCES FF_RISK_PROFILES(RISK_PROFILE_ID);

-- FF_POTENTIAL_FUNDS
CREATE TABLE FF_POTENTIAL_FUNDS(
    FUND_ID NUMBER(8) PRIMARY KEY,
    FUND_NAME VARCHAR2(30),
    FUND_DESCRIPTION VARCHAR2(200),
    Minimum_Investment_Required NUMBER(10,2),
    Maximum_Investment_Allowed NUMBER(10,2)
);

-- FF_FUND_ASSETS
CREATE TABLE FF_FUND_ASSETS (
    FUND_ASSET_CLASS_ID NUMBER(8) PRIMARY KEY,
    FUND_ID NUMBER(8),
    ASSET_CLASS_ID NUMBER(8),
    PERCENT_OF_FUND NUMBER(2,2)
);

ALTER TABLE FF_FUND_ASSETS ADD CONSTRAINT FK_FUND_ID_FUND_ASSETS_TABLE FOREIGN KEY (FUND_ID) REFERENCES FF_POTENTIAL_FUNDS (FUND_ID);
ALTER TABLE FF_FUND_ASSETS ADD CONSTRAINT FK_ASSET_CLASS_ID_FUND_ASSETS_TABLE FOREIGN KEY (ASSET_CLASS_ID) REFERENCES FF_ASSET_CLASSES (ASSET_CLASS_ID);

-- FF_CUSTOMER_FUNDS
CREATE TABLE FF_CUSTOMER_FUNDS (
    CUSTOMER_FUND_ID NUMBER(8) PRIMARY KEY,
    CUSTOMER_ID NUMBER(8),
    FUND_ID NUMBER(8),
    AMOUNT_INVESTED NUMBER(15,2)
);

ALTER TABLE FF_CUSTOMER_FUNDS ADD CONSTRAINT FK_CUST_ID_CUST_FUNDS_TABLE FOREIGN KEY (CUSTOMER_ID) REFERENCES FF_CUSTOMERS (CUSTOMER_ID);
ALTER TABLE FF_CUSTOMER_FUNDS ADD CONSTRAINT FK_FUND_ID_CUST_FUNDS_TABLE FOREIGN KEY (FUND_ID) REFERENCES FF_POTENTIAL_FUNDS (FUND_ID);

-- FF_ENGAGEMENT_FREQUENCIES
CREATE TABLE FF_ENGAGEMENT_FREQUENCIES (
    FREQUENCY_ID NUMBER(8) PRIMARY KEY,
    FREQUENCY_NAME VARCHAR2(20),
    FREQUENCY_CODE VARCHAR2(2)
);

-- FF_ENGAGEMENT_TYPES
CREATE TABLE FF_ENGAGEMENT_TYPES (
    ENGAGEMENT_TYPE_ID NUMBER(8) PRIMARY KEY,
    ENGAGEMENT_TYPE_NAME VARCHAR2(10),
    ENGAGEMENT_TYPE_CODE VARCHAR2(5)
);

-- FF_FUND_TARGETS
CREATE TABLE FF_FUND_TARGETS (
    FUND_ID NUMBER(8) PRIMARY KEY,
    ASSET_OBJECTIVE_ID NUMBER(8),
    ENGAGEMENT_TYPE_ID NUMBER(8),
    FREQUENCY_ID NUMBER(8),
    TARGET_DESCRIPTION VARCHAR2(100)
);

ALTER TABLE FF_FUND_TARGETS ADD CONSTRAINT FK_FUND_ID_FUND_TRGT_TABLE FOREIGN KEY (FUND_ID) REFERENCES FF_POTENTIAL_FUNDS (FUND_ID);
ALTER TABLE FF_FUND_TARGETS ADD CONSTRAINT FK_ASSET_OBJ_ID_FUND_TRGT_TABLE FOREIGN KEY (ASSET_OBJECTIVE_ID) REFERENCES FF_ASSET_OBJECTIVES (ASSET_OBJECTIVE_ID);
ALTER TABLE FF_FUND_TARGETS ADD CONSTRAINT FK_ENG_TYPE_ID_FUND_TRGT_TABLE FOREIGN KEY (ENGAGEMENT_TYPE_ID) REFERENCES FF_ENGAGEMENT_TYPES (ENGAGEMENT_TYPE_ID);
ALTER TABLE FF_FUND_TARGETS ADD CONSTRAINT FK_FREQ_ID_FUND_TRGT_TABLE FOREIGN KEY (FREQUENCY_ID) REFERENCES FF_ENGAGEMENT_FREQUENCIES (FREQUENCY_ID);

-- FF_CEP
CREATE TABLE FF_CEP (
    CUSTOMER_ID NUMBER(8) PRIMARY KEY,
    ENGAGEMENT_TYPE_ID NUMBER(8),
    FREQUENCY_ID NUMBER(8)
);

ALTER TABLE FF_CEP ADD CONSTRAINT FK_CUST_ID_CEP_TABLE FOREIGN KEY (CUSTOMER_ID) REFERENCES FF_CUSTOMERS (CUSTOMER_ID);
ALTER TABLE FF_CEP ADD CONSTRAINT FK_ENG_TYPE_ID_CEP_TABLE FOREIGN KEY (ENGAGEMENT_TYPE_ID) REFERENCES FF_ENGAGEMENT_TYPES (ENGAGEMENT_TYPE_ID);
ALTER TABLE FF_CEP ADD CONSTRAINT FK_FREQ_ID_CEP_TABLE FOREIGN KEY (FREQUENCY_ID) REFERENCES FF_ENGAGEMENT_FREQUENCIES (FREQUENCY_ID);
COMMIT;

-- temp
--SELECT COUNT(*) FROM FF_CUSTOMERS;
--SELECT COUNT(*) FROM FF_ASSET_OBJECTIVES;
--SELECT COUNT(*) FROM FF_CUSTOMER_ASSETS;
--SELECT COUNT(*) FROM FF_QUESTIONS;
--select count(*) from FF_RISK_PROFILES;
--SELECT COUNT(*) FROM FF_ANSWERS;
--SELECT COUNT(*) FROM FF_CUSTOMER_ANSWERS;
--SELECT COUNT(*) FROM FF_ASSET_CLASSES;
--SELECT COUNT(*) FROM FF_POTENTIAL_FUNDS;
--SELECT COUNT(*) FROM FF_FUND_ASSETS;
--SELECT COUNT(*) FROM FF_CUSTOMER_FUNDS;
--SELECT COUNT(*) FROM FF_ENGAGEMENT_FREQUENCIES;
--SELECT COUNT(*) FROM FF_ENGAGEMENT_TYPES;
--SELECT COUNT(*) FROM FF_FUND_TARGETS;
--SELECT COUNT(*) FROM FF_CEP;